services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-17.5-bookworm}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: views-sync
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    tmpfs:
      - /var/lib/postgresql/data
